server:
  port: 80
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost/zhguo
      username: root
      password: aabbcc570
      driver-class-name: com.mysql.cj.jdbc.Driver
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/zhguo
#    username: root
#    password: aabbcc570
#    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
      table-prefix: t_